"""
Dump findings-mode prompts for a single ticker to disk.

Writes data/dossiers/{ticker}/findings_prompts.json with three specialist
prompts (lever_findings, mispricing_findings, ir_sec_triangulation) ready
to dispatch. The findings_adversarial prompt is generated by the caller
after the specialist outputs are collected.

Usage:
    python scripts/dump_findings_prompts.py TICKER
    python scripts/dump_findings_prompts.py TICKER --include-adversarial
"""

import argparse
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS))

from agent_prompts import build_findings_prompts

DOSSIERS = SCRIPTS.parent / "data" / "dossiers"


def main():
    p = argparse.ArgumentParser()
    p.add_argument("ticker")
    p.add_argument("--include-adversarial", action="store_true",
                   help="Include the adversarial prompt (requires specialist_summaries)")
    p.add_argument("--specialist-summaries", default="",
                   help="Path to a file with the synthesized 3-specialist output")
    args = p.parse_args()

    summaries = ""
    if args.specialist_summaries:
        summaries = Path(args.specialist_summaries).read_text(encoding="utf-8")

    prompts = build_findings_prompts(args.ticker, specialist_summaries=summaries)

    out_dir = DOSSIERS / args.ticker.lower()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "findings_prompts.json"

    payload = {
        "ticker": args.ticker.upper(),
        "lever_findings": prompts["lever_findings"],
        "mispricing_findings": prompts["mispricing_findings"],
        "ir_sec_triangulation": prompts["ir_sec_triangulation"],
        "_context_excerpt": str(prompts["_context"])[:500],
    }
    if args.include_adversarial:
        payload["findings_adversarial"] = prompts["findings_adversarial"]

    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {out_path}  ({sum(len(v) for v in payload.values() if isinstance(v, str))} chars)")


if __name__ == "__main__":
    main()
